version: '3'

services:
  web-leaked:
    build: .
    command: python cherry.py
    volumes:
      - .:/code
    ports:
      - "8000:8000"
  load:
    build: .
    command: python check.py
    volumes: 
      - .:/code
    depends_on: 
      - web-leaked
    links:
      - web-leaked
